spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 50
    open-in-view: false

logging:
  level:
    root: info
    com.anonymouschat: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
